language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - graphviz

install: "pip install -r requirements.txt"
before_script: "find data -name *.json | xargs python trailmap/build_trail_graphs.py"
script: nosetests trailmap/tests.py