language: python
python:
  - "2.7"

install: "pip install -r requirements.txt"
before_script: "find trailmaps -name *.json | xargs venv/bin/python src/create_graph.py"
script: nosetests src/graph_tests.py